// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvKlCh-9lsqiVlS4ulgwKbj9eD6MfYS04',
    appId: '1:530541375342:web:a98bcc74fe5e5283935b7f',
    messagingSenderId: '530541375342',
    projectId: 'godseye-30504',
    authDomain: 'godseye-30504.firebaseapp.com',
    storageBucket: 'godseye-30504.appspot.com',
    measurementId: 'G-PSR2H9GE8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEkEsW2Ahx_NqOW8_4XtzSO6-vDSmohZo',
    appId: '1:530541375342:android:1d68eca6ab76d762935b7f',
    messagingSenderId: '530541375342',
    projectId: 'godseye-30504',
    storageBucket: 'godseye-30504.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2JBZnA6W-3IKg_MGNGM2Vzthfb1q4rDk',
    appId: '1:530541375342:ios:47a255ac8e1f4948935b7f',
    messagingSenderId: '530541375342',
    projectId: 'godseye-30504',
    storageBucket: 'godseye-30504.appspot.com',
    iosBundleId: 'com.dn.godseyeev1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2JBZnA6W-3IKg_MGNGM2Vzthfb1q4rDk',
    appId: '1:530541375342:ios:47a255ac8e1f4948935b7f',
    messagingSenderId: '530541375342',
    projectId: 'godseye-30504',
    storageBucket: 'godseye-30504.appspot.com',
    iosBundleId: 'com.dn.godseyeev1',
  );
}
